<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>AM_Business_Rule</name>
  <uuid>ebffb4a1-8ebf-4df3-842e-b86122635e41</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	Input 
then
	set decision to "Decision is working" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
